### ISSUE TITLE
SQL().GET(&time.Time)的问题 

### ISSUE THREAD

**Issue by usernameisnull** [go-xorm/xorm#1107]
sql := "SELECT create_date From client WHERE report_id = ?"
var MaxDate time.Time
result,err:=conn.SQL(sql, 98977).Get(&MaxDate)
fmt.Println(result,err,MaxDate)

错误
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x7bcc80, 0xc04216f380, 0x36, 0x4c1c01, 0x7c5b20, 0x7bcc80)
	G:/Go/src/reflect/value.go:942 +0x1e4
reflect.Value.Interface(0x7bcc80, 0xc04216f380, 0x36, 0x7bcc80, 0xc04216f380)
	G:/Go/src/reflect/value.go:931 +0x4b
github.com/go-xorm/xorm.(*Engine).mapType(0xc0421b6340, 0x8395a0, 0xc04216f380, 0x199, 0x839500, 0x199, 0xc04206fc08)
	E:/gopath/src/github.com/go-xorm/xorm/engine.go:1003 +0xc07
github.com/go-xorm/xorm.(*Engine).autoMapType(0xc0421b6340, 0x8395a0, 0xc04216f380, 0x199, 0x0, 0x0, 0x0)
	E:/gopath/src/github.com/go-xorm/xorm/engine.go:817 +0x189
github.com/go-xorm/xorm.(*Statement).setRefBean(0xc04209b618, 0x83a920, 0xc04216f380, 0x8395a0, 0xc04216f380)
	E:/gopath/src/github.com/go-xorm/xorm/statement.go:218 +0x70
github.com/go-xorm/xorm.(*Session).get(0xc04209b600, 0x83a920, 0xc04216f380, 0x1, 0x1, 0xc04209b600)
	E:/gopath/src/github.com/go-xorm/xorm/session_get.go:35 +0xbd3
github.com/go-xorm/xorm.(*Session).Get(0xc04209b600, 0x83a920, 0xc04216f380, 0xc042168f00, 0x0, 0x0)
	E:/gopath/src/github.com/go-xorm/xorm/session_get.go:23 +0x6c

**Comment by BetaCat0** [comment]
感谢反馈，目前来说可以尝试用一个``struct``包一下这个结果，或是直接以``string``形式读出，再做转换。``time.Time``的直接读取问题我们将会尽快解决，也欢迎您直接提出PR。
