### ISSUE TITLE
'xorm:"updated"' always fail when update with map data in transaction

### ISSUE THREAD

**Issue by fuxiaohei** [go-xorm/xorm#312]
```go
package main

import (
	"github.com/go-xorm/xorm"
	_ "github.com/mattn/go-sqlite3"
	"time"
)

type TestDb struct {
	Id         int64
	Content    string
	UpdateTime time.Time `xorm:"updated"`
}

func main() {
	engine, err := xorm.NewEngine("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}
	engine.ShowSQL = true
	if err = engine.Sync2(new(TestDb)); err != nil {
		panic(err)
	}

	sess := engine.Table(new(TestDb))
	sess.Begin()
    defer sess.Close()
	if _, err = sess.Update(map[string]interface{}{
		"content": "ababababab",
	}); err != nil {
		panic(err)
	}
	if err = sess.Commit(); err != nil {
		panic(err)
	}
}
```

panic stack

```
[xorm] [info]  2015/11/02 11:50:51.158866 [sql] SELECT name FROM sqlite_master WHERE type='table' []
[xorm] [info]  2015/11/02 11:50:51.159866 [sql] SELECT sql FROM sqlite_master WHERE type='table' and name = ? [test_db]
[xorm] [info]  2015/11/02 11:50:51.160866 [sql] SELECT sql FROM sqlite_master WHERE type='index' and tbl_name = ? [test_db]
[xorm] [info]  2015/11/02 11:50:51.160866 [sql] BEGIN TRANSACTION
[xorm] [info]  2015/11/02 11:50:51.160866 [sql] UPDATE `test_db` SET `content` = ?, `update_time` = ?  [args] [ababababab 2015-11-02 03:50:51]
[xorm] [info]  2015/11/02 11:50:51.160866 [sql] ROLL BACK
panic: runtime error: hash of unhashable type map[string]interface {}

goroutine 1 [running]:
github.com/go-xorm/xorm.(*Session).Update(0xc082069400, 0x744560, 0xc082055cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        E:/GOPATH/src/github.com/go-xorm/xorm/session.go:3766 +0x3479
main.main()
        E:/Go_Fuxiaohei/src/main.go:30 +0x336

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc082094a00)
        c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
        c:/go/src/database/sql/sql.go:481 +0x33d
```

it seems set map[string]interfaced{} to map key in session.afterUpdateBeans.

**Comment by lunny** [comment]
OK. I have found the problem.

**Comment by daivem** [comment]
期待可以早点修复

**Comment by lunny** [comment]
But @fuxiaohei , your codes have some wrong usage, corrected is below:
```Go
package main

import (
	"time"

	"github.com/go-xorm/xorm"
	_ "github.com/mattn/go-sqlite3"
)

type TestDb struct {
	Id         int64
	Content    string
	UpdateTime time.Time `xorm:"updated"`
}

func main() {
	engine, err := xorm.NewEngine("sqlite3", "test.db")
	if err != nil {
		panic(err)
	}
	engine.ShowSQL = true
	if err = engine.Sync2(new(TestDb)); err != nil {
		panic(err)
	}

	sess := engine.NewSession()
	defer sess.Close()

	if err := sess.Begin(); err != nil {
		panic(err)
	}

	if _, err = sess.Table(new(TestDb)).Update(map[string]interface{}{
		"content": "ababababab",
	}); err != nil {
		panic(err)
	}
	if err = sess.Commit(); err != nil {
		panic(err)
	}
}
```
