### ISSUE TITLE
xorm - 4.3 - panic: gob: registering duplicate names for models 

### ISSUE THREAD

**Issue by debraj-manna** [go-xorm/xorm#423]
I am getting the below exception with xorm - 4.3 and golang 1.4.2. Any idea what could be going wrong? Is this some known issue xorm - 4.3 or some thing other going wrong?

```
panic: gob: registering duplicate names for models.SalesOrderItemAttribute: "*models.SalesOrderItemAttribute" != "order-subscriber/models.SalesOrderItemAttribute"

goroutine 71 [running]:
encoding/gob.RegisterName(0xc208120750, 0x2f, 0x9d0cc0, 0xc2084dafc0)
	/usr/local/go/src/encoding/gob/type.go:832 +0x568
encoding/gob.Register(0x9d0cc0, 0xc2084dafc0)
	/usr/local/go/src/encoding/gob/type.go:884 +0x20f
github.com/go-xorm/xorm.(*Engine).GobRegister(0xc20856e3f0, 0x9d0cc0, 0xc2084dafc0, 0x9d0cc0)
	/home/jabong-release/go/src/github.com/go-xorm/xorm/engine.go:679 +0x32
github.com/go-xorm/xorm.(*Engine).autoMapType(0xc20856e3f0, 0x9d0cc0, 0xc2084dafc0, 0x59, 0x59)
	/home/jabong-release/go/src/github.com/go-xorm/xorm/engine.go:670 +0x290
github.com/go-xorm/xorm.(*Session).innerInsertMulti(0xc208606fc0, 0x86d0c0, 0xc2081f5e80, 0x8, 0x0, 0x0)
	/home/jabong-release/go/src/github.com/go-xorm/xorm/session.go:2071 +0x30c
github.com/go-xorm/xorm.(*Session).Insert(0xc208606fc0, 0xc2086153a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/jabong-release/go/src/github.com/go-xorm/xorm/session.go:2034 +0x260
github.com/go-xorm/xorm.(*Engine).Insert(0xc20856e3f0, 0xc2086153a0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/jabong-release/go/src/github.com/go-xorm/xorm/engine.go:1284 +0x99
order-subscriber/dao.InsertItemAttributes(0xc208223180, 0x8, 0xa, 0x0, 0x0, 0xd5a938, 0x0, 0xd5a938, 0x0, 0xd5a938, ...)
	/var/lib/jenkins/jobs/CI_order-subscriber_pkg_creation/workspace/src/order-subscriber/dao/dao.go:236 +0x35d
```

**Comment by lunny** [comment]
Hi, this is because xorm will register the struct to gob automatically for cache use. If you have register it on the same application, gob will panic.

**Comment by debraj-manna** [comment]
Can you please explain a bit more? I did not register it in gob again on the same application. The code that is throwing the error is the above.

**Comment by debraj-manna** [comment]
Is the issue related to the below issue:-

https://groups.google.com/forum/#!topic/golang-nuts/VnFs2Cv0_UY

If yes how can I get around this?

**Comment by lunny** [comment]
OK. I see, maybe your problem is "*models.SalesOrderItemAttribute" != "order-subscriber/models.SalesOrderItemAttribute". 
You imported the same struct from different code copy or path.

**Comment by debraj-manna-jabong** [comment]
Hmm ... I checked the code path but that is not the case. Also if that is the issue then the issue would have come every time. 

Is the issue related to [this](https://groups.google.com/forum/#!topic/golang-nuts/VnFs2Cv0_UY) because when it is failing  `* SalesOrderItemAttribute.IdSalesOrderItemAttribute` is also having value 0.
