### ISSUE TITLE
Panic on engine.Find (  invalid memory address or nil pointer dereference )

### ISSUE THREAD

**Issue by toni-moreno** [go-xorm/xorm#432]
I'm new on the xorm engine and I'm trying to load data from one single table to a single struct. And I don't know how to fix, help needed please.

## The Panic ##

Here the panic  after engine.Sync was ok

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x5418e6]

goroutine 1 [running]:
panic(0xbbf380, 0xc82000a110)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/go-xorm/xorm.(*Engine).autoMapType(0x0, 0xbcad00, 0xc8201b7ea0, 0x199, 0xc8201b7ea0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/engine.go:848 +0x66
github.com/go-xorm/xorm.(*Session).Find(0xc8201c98c0, 0xa66d40, 0xc8201b7e80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/session.go:1115 +0x42d
github.com/go-xorm/xorm.(*Engine).Find(0x0, 0xa66d40, 0xc8201b7e80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/engine.go:1540 +0xa9
main.(*DatabaseCfg).LoadConfig(0x124fa40)
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/model.go:210 +0x89
main.init.1()
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/main.go:149 +0x76f
main.init()
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/webserver.go:199 +0x3bc

````

## The code ##

````

type MeasurementFieldCfg struct {
	idMeasurementCfg string `xorm:"id_measurement_cfg"`
	idMetricCfg      string `xorm:"id_metric_cfg"`
}
..
..
..
var MeasureMetric []*MeasurementFieldCfg
if err = engine.Find(&MeasureMetric); err != nil {
	log.Warnf("Fail to get Measurements Metric relationship data: %v\n", err)
}
````

## The data ##

Data has been inserted into a sqllite db. 

````
sqlite> .schema measurement_field_cfg
CREATE TABLE `measurement_field_cfg` (`id_measurement_cfg` TEXT NULL, `id_metric_cfg` TEXT NULL);
sqlite> select * from measurement_field_cfg;
linux_cpu|Linux_user_CPU_percent
linux_cpu|Linux_system_CPU_percent
linux_cpu|Linux_idle_CPU_percent
linux_ports|ifHCInOctets
linux_ports|ifHCOutOctets
linux_ports|ifHCInUcastPkts
linux_ports|ifHCOutUcastPkts
network_32bits|ifOctets
network_32bits|ifOutOctets
````

Anybody that could  help me to locate the error and fix it?

Thank you very much

**Comment by lunny** [comment]
Hi, Your think maybe you have to define the struct
```Go
type MeasurementFieldCfg struct {
    IdMeasurementCfg string `xorm:"id_measurement_cfg"`
    IdMetricCfg      string `xorm:"id_metric_cfg"`
}
```
Because `reflect` cannot visit struct's private fields.

**Comment by toni-moreno** [comment]
I did the change you suggested and  I got the same result.

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x5418e6]

goroutine 1 [running]:
panic(0xbbf380, 0xc82000a110)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/go-xorm/xorm.(*Engine).autoMapType(0x0, 0xbcad00, 0xc8201b3ea0, 0x199, 0xc8201b3ea0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/engine.go:848 +0x66
github.com/go-xorm/xorm.(*Session).Find(0xc8201c58c0, 0xa66d40, 0xc8201b3e80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/session.go:1115 +0x42d
github.com/go-xorm/xorm.(*Engine).Find(0x0, 0xa66d40, 0xc8201b3e80, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/developer/src/gospace/src/github.com/go-xorm/xorm/engine.go:1540 +0xa9
main.(*DatabaseCfg).LoadConfig(0x124fa40)
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/model.go:210 +0x89
main.init.1()
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/main.go:149 +0x76f
main.init()
	/home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/webserver.go:199 +0x3bc
````

Any other suggestion that I can do?

Thank you very much

**Comment by toni-moreno** [comment]
You can see complete code at.

https://github.com/toni-moreno/snmpcollector/blob/toml_to_sqldb_migration/pkg/model.go#L210

I'm have not idea on how to load all data from db to internal configuration maps.

Thank you very much.

**Comment by lunny** [comment]
OKay. I found your code problem. You call `InitDB(cfg)`, so cfg is copied to the function, and you set `x` to cfg, but it will not be passed to the external of the function. You have to give a pointer parameter to `InitDB(&cfg)`.

**Comment by toni-moreno** [comment]
Yes , you are right I've fixed the problem.
Sorry for this stupid mistake.
