### ISSUE TITLE
panic Query

### ISSUE THREAD

**Issue by v-grabko** [go-xorm/xorm#483]
Mysql. 

```
res, err := engine.Query("select * from tranzaction")
if err != nil {
	log.Fatal(err)
}
log.Println(res)
```
panic:
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8145af5]

goroutine 1 [running]:
panic(0x8413a00, 0x1890c010)
	/usr/local/go/src/runtime/panic.go:500 +0x331
github.com/go-xorm/xorm.(*Session).queryPreprocess(0x18972640, 0x18949e74, 0x0, 0x0, 0x0)
	/home/vgrabko/go/src/github.com/go-xorm/xorm/session.go:2124 +0x185
github.com/go-xorm/xorm.(*Session).query(0x18972640, 0x84513a1, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vgrabko/go/src/github.com/go-xorm/xorm/session.go:2133 +0x61
github.com/go-xorm/xorm.(*Session).Query(0x18972640, 0x84513a1, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vgrabko/go/src/github.com/go-xorm/xorm/session.go:2199 +0xd1
github.com/go-xorm/xorm.(*Engine).Query(0x0, 0x84513a1, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vgrabko/go/src/github.com/go-xorm/xorm/engine.go:1468 +0xaf
github.com/clonplaytox/migrations/models.GetRollbackTranzaction(0x0, 0x0)
	/home/vgrabko/go/src/github.com/clonplaytox/migrations/models/store.go:63 +0x5a
main.main()
	/home/vgrabko/.local/share/data/liteide/goplay.go:9 +0x1e
exit status 2
```

As the right thing to  ORDER BY without Where?

**Comment by lunny** [comment]
Please check if engine is not nil!

**Comment by v-grabko** [comment]
engine not nil. 

Not only this function operates https://github.com/ClonPlaytox/migrations/blob/master/models/store.go#L62

**Comment by lunny** [comment]
```
github.com/go-xorm/xorm.(*Engine).Query(0x0, 0x84513a1, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vgrabko/go/src/github.com/go-xorm/xorm/engine.go:1468 +0xaf
```
First parameter is 0x0. It means *Engine is nil.

**Comment by v-grabko** [comment]
and how to fix it? I do not understand what it is zero engint.

**Comment by v-grabko** [comment]
sorry
