### ISSUE TITLE
Cannot insert to a table with only an autoincrement id

### ISSUE THREAD

**Issue by goofansu** [go-xorm/xorm#573]
``` go
type Account struct {
	Id int64 `xorm:"pk autoincr"`
}

engine.Insert(&Account{})
```

Error

```
panic: runtime error: slice bounds out of range

goroutine 27 [running]:
github.com/go-xorm/xorm.(*Session).innerInsert(0xc42033b8c0, 0x13f2fe0, 0xc420360520, 0x0, 0x0, 0x0)
	/Users/suyejun/go/src/github.com/go-xorm/xorm/session_insert.go:346 +0x24e8
github.com/go-xorm/xorm.(*Session).Insert(0xc42033b8c0, 0xc4201c1810, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/suyejun/go/src/github.com/go-xorm/xorm/session_insert.go:49 +0x325
github.com/go-xorm/xorm.(*Engine).Insert(0xc420114140, 0xc4201c1810, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/suyejun/go/src/github.com/go-xorm/xorm/engine.go:1394 +0xa4
....
...
exit status 2
```

**Comment by lunny** [comment]
How do a SQL to do that?

**Comment by goofansu** [comment]
@lunny 

in MySQL

```sql
insert into auto_ids values();
```

or

```sql
insert into auto_ids(id) values(NULL);
```
