### ISSUE TITLE
go 1.8.1 error

### ISSUE THREAD

**Issue by ddatsh** [go-xorm/xorm#574]
win10 x64
go 1.8.1
编译gogs develop分支最新版,目前commitId   6500aafc
git clone时
```
git clone 
Cloning into 'xx'...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x7bddc8]

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).autoMapType(0x0, 0xebb060, 0xc042214200, 0x199, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:779 +0x78
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Statement).setRefValue(0xc04225a298, 0xebb060, 0xc042214200, 0x199)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/statement.go:219 +0x7a
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Session).Get(0xc04225a280, 0xebb8e0, 0xc042214200, 0x200, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/session_get.go:23 +0xf3
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).Get(0x0, 0xebb8e0, 0xc042214200, 0x0, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:1467 +0x9a
github.com/gogits/gogs/models.GetUserByName(0xc04206f841, 0x6, 0xec8759, 0x4, 0x1)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/models/user.go:928 +0xc5
github.com/gogits/gogs/cmd.runServ(0xc042178280, 0x0, 0xc042178280)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/cmd/serv.go:155 +0x2c2
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xdaefa0, 0xf10850, 0xc042178280, 0xc042034600, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xc0
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xec9401, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf004e7, 0x2f, 0x0, ...)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb79
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc042032ea0, 0xc04203e100, 0x4, 0x4, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d7
main.main()
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/gogs.go:41 +0x3f1
fatal: Could not read from remote repository.
```
go 1.8
go 1.7.5编译没问题

**Comment by lunny** [comment]
xorm的版本多少？

**Comment by ddatsh** [comment]
xorm v0.6.0.1022

**Comment by ddatsh** [comment]
升到最新的 就好了
