### ISSUE TITLE
insert时app崩溃

### ISSUE THREAD

**Issue by kpvt001** [go-xorm/xorm#658]
```
Exception 0xc0000005 0x8 0xe912f8 0xe912f8
PC=0xe912f8
signal arrived during external code execution

github.com/mattn/go-sqlite3._Cfunc__sqlite3_step(0x16b4d58, 0xc04211ffb8, 0xc0421c6000, 0x0)
        github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:241 +0x54
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec.func4(0x16b4d58, 0xc04211ffb8, 0xc0421c6000, 0xc04200c300)
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:966 +0x7b
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec(0xc0421c2240, 0x15f81d0, 0xc04200c300, 0xc042110e00, 0xb, 0xb, 0x0, 0x0, 0x0, 0x0)
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:966 +0x1a2
github.com/mattn/go-sqlite3.(*SQLiteConn).exec(0xc0420350e0, 0x15f81d0, 0xc04200c300, 0xc0421c05b0, 0xc4, 0xc042110e00, 0xb, 0xb, 0x4b080b, 0xeeeed8, ...)
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:503 +0x300
github.com/mattn/go-sqlite3.(*SQLiteConn).ExecContext(0xc0420350e0, 0xe994a0, 0xc04200c300, 0xc0421c05b0, 0xc4, 0xc042110c40, 0xb, 0xb, 0x15f8158, 0x4f4110, ...)
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3_go18.go:40 +0x262
database/sql.ctxDriverExec(0xe994a0, 0xc04200c300, 0x15f8158, 0xc0420350e0, 0xc0421c05b0, 0xc4, 0xc042110c40, 0xb, 0xb, 0x4ce225, ...)
        C:/Go/src/database/sql/ctxutil.go:31 +0x294
database/sql.(*DB).exec.func2()
        C:/Go/src/database/sql/sql.go:1199 +0xa0
database/sql.withLock(0xe962e0, 0xc042192d90, 0xc042069538)
        C:/Go/src/database/sql/sql.go:2545 +0x6c
database/sql.(*DB).exec(0xc0421acaa0, 0xe994a0, 0xc04200c300, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0xc042120701, 0x0, ...)
        C:/Go/src/database/sql/sql.go:1200 +0x523
database/sql.(*DB).ExecContext(0xc0421acaa0, 0xe994a0, 0xc04200c300, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0x30, 0x0, ...)
        C:/Go/src/database/sql/sql.go:1165 +0xc3
database/sql.(*DB).Exec(0xc0421acaa0, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0xc042120780, 0x100000000000199, 0xc042036f20, 0xc042069738)
        C:/Go/src/database/sql/sql.go:1179 +0x8c
github.com/go-xorm/xorm.(*Session).innerExec(0xc04213cb40, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0xc0420ae100, 0xc0421c2180, 0x1f, 0xed0760)
        F:/gopath/src/github.com/go-xorm/xorm/session_raw.go:286 +0x8f
github.com/go-xorm/xorm.(*Session).exec.func1(0x10, 0x10, 0xc04211ff40, 0x0)
        F:/gopath/src/github.com/go-xorm/xorm/session_raw.go:306 +0x10c
github.com/go-xorm/xorm.(*Engine).logSQLExecutionTime(0xc0421acb40, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0xc0420698f8, 0xc4, 0xc0420ae0f0, 0x0, ...)
        F:/gopath/src/github.com/go-xorm/xorm/engine.go:304 +0x5b
github.com/go-xorm/xorm.(*Session).exec(0xc04213cb40, 0xc0421c05b0, 0xc4, 0xc04207ae70, 0xb, 0xb, 0xc4, 0xb, 0xc04207ae70, 0xb)
        F:/gopath/src/github.com/go-xorm/xorm/session_raw.go:309 +0x200
github.com/go-xorm/xorm.(*Session).innerInsert(0xc04213cb40, 0xab3e20, 0xc042120780, 0x0, 0x0, 0x0)
        F:/gopath/src/github.com/go-xorm/xorm/session_insert.go:486 +0xfdd
github.com/go-xorm/xorm.(*Session).Insert(0xc04213cb40, 0xc042069e38, 0x1, 0x1, 0x0, 0x0, 0x0)
        F:/gopath/src/github.com/go-xorm/xorm/session_insert.go:49 +0x32c
github.com/go-xorm/xorm.(*Engine).Insert(0xc0421acb40, 0xc042069e38, 0x1, 0x1, 0x0, 0x0, 0x0)
        F:/gopath/src/github.com/go-xorm/xorm/engine.go:1392 +0xab
project/db.InsertShippingLine(0xc042120780, 0xc042120780, 0x1)
        F:/gopath/src/project/db/ShippingLine.go:24 +0x7c
project/db.Test()
        F:/gopath/src/project/db/test.go:9 +0x14a
main.main()
        F:/gopath/src/project/main.go:21 +0x60

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0421acaa0)
        C:/Go/src/database/sql/sql.go:837 +0x51
created by database/sql.Open
        C:/Go/src/database/sql/sql.go:582 +0x219

goroutine 7 [select]:
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec.func3(0x15f81d0, 0xc04200c300, 0xc042035140, 0x1696648)
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:958 +0x11c
created by github.com/mattn/go-sqlite3.(*SQLiteStmt).exec
        F:/gopath/src/github.com/mattn/go-sqlite3/sqlite3.go:963 +0x13f
rax     0x0
rbx     0x3
rcx     0x1c0
rdi     0x1
rsi     0x1697650
rbp     0x0
rsp     0x15ef948
r8      0x1
r9      0x0
r10     0x0
r11     0x246
r12     0x1696648
r13     0x1
r14     0x40
r15     0x0
rip     0xe912f8
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by lunny** [comment]
更新下sqlite的驱动看下

**Comment by kpvt001** [comment]
这两天刚通过`go get`和`go install`安装的`go-sqlite3`

**Comment by lunny** [comment]
把你的示意代码贴下

**Comment by kpvt001** [comment]
main.go
```
e1:=db.InitDbInstances()
	if e1!=nil{
		fmt.Println("init db error:"+e1.Error())
	}
	db.Test()
```

```
func Test(){
	var err error
	fmt.Println("db test")
	InitDbInstances()
	vesselsDb.Sync2(new(ShippingLine))
	err=InsertShippingLine(&ShippingLine{VesselPrefix:"v",VesselName:"n",From:1,To:33,AdditionalMessage1:3,CaptinName:"captin"})
	if err!=nil{
		fmt.Println(err.Error())
	}
}
```

```
var vesselsDb *xorm.Engine

func InitDbInstances() error{
	var err error
	vesselsDb, err=xorm.NewEngine("sqlite3", "./test.db")
	return err
}
```
```
type ShippingLine struct {
	Id int
	VesselPrefix string
	VesselName string
	CaptinName string
	Purpose int
	Camp int
	From int
	To int
	StartTimeStamp int
	BaseSpeed int
	AdditionalMessage1 int
}

func InsertShippingLine(sl *ShippingLine) error{
	_,err:=vesselsDb.Insert(sl)
	return err
}
```

**Comment by lunny** [comment]
看着没什么问题，可能还是 github.com/mattn/go-sqlite3 的问题，你到它的 issues 里贴下吧。

**Comment by kpvt001** [comment]
只用database/sql的接口也出错。
